language: php
env:
  global:
  - secure: bmXhD9ypWH0LF8hSRmT8E7CiBVj8mHdWzZBgif8LTMYwkJatBykSPmS+Je2KzIrx764KiNGxnMAGyfyEH1nG0qM8FzjbERgTbs6YQdBwIC2V/eCVnqgXWLipgZ2HL9uE+Z9rHK07og87P0H1YQWZLjWgxvF90h2pRpoPOEd6SfDSp51An6GblwZS3spNRl/1QM1p045qTlX11jxZFe82qaODmupiOVK/6T9nIQVDK+FqxRS5JaWehcV3wALUoKftz2h/NqUOzUheYD4ZzEouSc/tja2IV+uTBJ1np8/ibBcQJ06/WVgOvLsUornyOmvdWmFaNiiKuFRmHjfPkpCXFPOgCNK/KRjwBN4tszRKSuLleWs+vQreF803d6OUi7+WHXTyB47Ayi9foI21XaqC31DBhyw1v9tzEIyL0ylZgBO4/Ltp1L/Mc3d1bX0v1VD+KFgLT75dMbdundar9sDAPrLRaQ2XdrGaCJXRP+4kUFwW1vGCPHy/7QxkSeB7rVyfzfkZwJMVYX1xwYkjiNtD+kKSgJhy6W1IORw2D5rhpmPg2g3RnLo7NsB9wzeZzZkn7JG0vYnN3QLKsJlQK1nXsRxyBtAdb9FgzOspv8hFnD3EeNgX5YhNkicmkZDWvsZjYtmHqkeKplU35tlkwfd7xVoDA2xouXqdRHsT2CJLoS8=
  - secure: umdRr4G2+P8BMectFhWty/ZwhDRTsfcG8N6g+57S3QqXvFf93C2xcF6EKvr2UlotjEANJXIkS3k10sLxFg5CvwypaCdLzeeI21JIQpllWc3D5PlKbR6ufNGxeuVB26gyYHjN6+jYU1fv0ua2SW/Q75zwUHaImV3QPkkrq8gLj09L8G+5wvUdbrznNmDgPdFvCIlTpy9nejCrzcEpy9XdTRp9SlXbIQ5qzIWYDzvd0TPEDsx9YVkS8ipIUez0hWW7fgK/tIIChSon0XbJcRiNoljitCoz7qCRCvi6yMvHfuQCfk3lo1mAeX6nKcQtiIFcE2WQJGqI6mc4w6dygXwB4jN45V1O3WuZhmIDQgvJSoUrEYlsPdArJS9cfQRgn8XBKr9znCOE11J2PLpqBciLshQV/ibp9btryQy/6qBzDTVvEXZXdF2o0n8Jd1+qO54tc0dqdSDMiYi5YKYn9d2076DCN3dfPEPd7Gbb/ATq+MlaLXAIF3NXugqOAwcXwcNyrIPoiSUY+LT5NYeeOQaFP6bazW4hVNP08EiZVrIbry/ikfFApVD/Y8YBR/7LbQMj1ZxeTdI7J5w1LmyUlJjxgeMXAddz3RMcmi/s1NeZjd+gnm6NznQQGy/eZZrikA8qRTI4D9dHsXkRo7Lp2ovB89n8Yii1Er80XUX5k2sjTqQ=
  - secure: cyir1KlmvuVl3oFzLqJDd8jqS8AuklYu4OWiHLIwJiQFGzC1gEZvT8L5W+b/+cv21kvQ7lpte363TIhemF6qqHeKTdMkJA/Nf1ryo0tYGfMVI7+Zmk1UvKqzoHvlS/tHr3j6e302U4hTmDvPG7g4pa2j6VoBkCdgbm7vXB4TVLClxkjw2+RlKlaj7Ed37OaapplhMG8J8DnXcWAF8jaNUbQVEQCQNe5aHaBFa6KlYWEtpKzgyGI6zyJqay9lWyce1mZrC9rP5jv1Z3Rex3DYWeCfbxhlbDo8qSDUoCwo/2JoDGoeGAGuSl/wyWSmx9fF+OQODX2yrUsMB2aazVIgzPHv0XyKbqEjTJ3+YlSn0e5JD2knNZCaU9hhWvDdjFCnKU+LgL6ubmVKd9j3+ZRwO7Rj8gb1ORwlYTYFQE5u1Yakvo7lZJz32Np6YFia/JwhiebZdirl0qm6oOnh8myia9u+4xzUlJR33v0tEaPyMOm7igWc4QwCLa523vl/sxjPUy2a41ZFjmndX6W5yP5qdGf48QVgq2ZEDQPHNPrl5ZODPMRMKa7ACMPZVCa/RVWK5vtkUKHlVaCO3OrjSHch8wExjfWDCKJai57Nm0mikPtX95njhAhMAaY/lfuBE9SGFec+LH5XdL8bwpEMfGBbnJYSmB0Sv9sYp3XFINnO/pc=
  - secure: BNMKP+BYaXKPpx3ETvsTwN0AVbT+0jh6j3914rTyTcDzUiWSaWSBzoOGS9gy/+bnmAM6n6EbmB4ZLssPNW6LviOI1OJkknS7pdEsLmNFSNFRbem9FgAWC2Crl72e1FLMIsWEY1qp1Y1XDJ4fkTBsacCG9GJv8Xpm2oNWtuHHvAjLMu3Q4HT/h1WFA9a+6BD9C1k6HPR4MLQE+SUzNVC3YXlArRJui1cZOMmbag6hJAcIuH20+2VRD/zbwnz+7SAHQhUt/4hXpSROg+eMxwxuwXUhwJXRikObh+UJQjwe2fABfEfsfm0+7eqFoMg8m7lntaE3wj4z/Qw3HsBH+w95Xt/MPsrOr/IZ2M04W/hB8o5GZWg8LmPiB97ssQJ48KZh9qgDhyTn5d4znImeATZQKNCDQgTa+cEynEHYCILHtKzE3EfqA5GYBoKyLvexuOxzqNQcYW0DX1X0CRHP3bo4WnFb+dqKIl1TIlu+K1J4iaeyzFRi2wr2FtY+q9uZMdLw/d7GYkNHh8PsoWxRhVPAeE+ht+5bxp3ZUQZ3NMIacptGSX2ZVZJAsEsEdNC2UC7HRq14Qw7Gq6GucLZZQxkF55eWwPx8QkjnsyIEWyLI8AExMKXooRasvNvBppUzEZ5kLVZac78D5OOisxd+p11uRWRKZWhgvK4eQM3+AViLxK0=
php:
- '7.0'
before_script:
- composer self-update
- composer install --prefer-source --no-interaction
script: phpunit
notifications:
  on_success: never
  on_failure: always
addons:
  apt:
    packages:
    - sshpass
after_success:
- composer install --no-dev -o
- cd ..
- BUILD_FILE=`date "+%Y%m%d_%H%M%S"`.tgz
- echo $BUILD_FILE
- tar -czf $BUILD_FILE laravel-nutri-api
- export SSHPASS=$DEPLOY_PASS
- sshpass -e scp $BUILD_FILE $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
